Revert "use a working mozillians-client", which didn't work
I suspect buggy npm; result was "Error: Cannot find module 'mozillians-client''

This reverts commit 606069e83170ad02e9f9a1d2566f0af609ade868.